name: Test math_functions.py

on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'feature-**'

jobs: 
  test_math_functions:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: demo some shell commands
        run: | 
          echo $ ls-la
          ls -la
          echo $ pwd
          pwd
          echo $ whomi
          whoami
      - name: Install pytest
        run: |
          echo "$ pip install pytest"
          pip install pytest
          echo "$ pytest --version"
          pytest --version
      - name: Run calc test
        run: |
          echo "$ cd cicd"
          cd cicd
          echo "pytest"
          pytest



  